version = "0.2"

[phases]
[phases.install]
runtime-versions = { java = "corretto21" }
commands = [
  "echo Installing Maven..."
]

[phases.pre_build]
commands = [
  "echo Logging in to Docker hub...",
  "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
]

[phases.build]
commands = [
  "echo Building, Testing and packaging the application...",
  "mvn package"
]

[phases.post_build]
commands = [
  "echo Build, Testing and packaging completed."
]

[artifacts]
files = ["target/*.jar"]
discard-paths = true

[cache]
paths = ["/root/.m2/**/*"]
